version: '3'

services:
  auth-tool:
    container_name: authoring-tool
    image: idea/authoring-tool
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:80'
